name: "NuGet Deploy"

on: 
  push:
    branches: [ "main" ]

env:
  PROJECT_PATH: "src/Atlas.Core/Atlas.Core.csproj"
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        
      - name: "Install .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
        
      - name: "Restore packages"
        run: dotnet restore ${{env.PROJECT_PATH}}
        
      - name: "Build"
        run: dotnet build ${{env.PROJECT_PATH}} --no-restore --configuration Release
      
      - name: "Create Package"
        run: dotnet pack ${{env.PROJECT_PATH}} --no-restore --no-build --configuration Release --include-symbols --output ${{env.PACKAGE_OUTPUT_PATH}}
        
      - name: "Publish to NuGet"
        run: dotnet nuget push ${{env.PACKAGE_OUTPUT_PATH}}\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s ${{env.NUGET_SOURCE_URL}}
